Fix a build error (#137)
The following build error occurs:
```
In file included from ../../triple_banana/modules/public/manifest/manifest.cc:10:
In file included from ../../triple_banana/modules/public/interfaces.h:8:
In file included from ../../triple_banana/modules/public/connector.h:10:
../../content/child/child_thread_impl.h:23:10: fatal error: 'content/common/associated_interfaces.mojom.h' file not found
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

It is caused because the connector.h used content internal API directly.

Refs: none